name: Deploy to S3

on:
  push:
    branches:
      - main

env:
  BUCKET_NAME: 'ab-hub-frontend-bucket'
  AWS_REGION: 'us-east-1'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: github-deploy-session
          role-to-assume: arn:aws:iam::383548480552:role/github-actions-role

      - name: Deploy to S3
        run: |
          aws s3 sync ./build/ s3://${{ env.BUCKET_NAME }}
